name: mobilecrypto
description: "MobileCrypto â€” Achat et vente de cryptomonnaies via Mobile Money en Afrique."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon_beta.png

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon_beta.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0F172A"
  image: assets/icon/app_icon_beta_02.png
  android: true
  ios: true
